[package]
name = "metal-llvm"
version = "0.1.0"
edition = "2021"
description = "The Metal LLVM backend implementation."

[dependencies]
metal-ast = { workspace = true }
llvm-sys = { version = "191" }
