[package]
name = "metal-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
rowan = { workspace = true }
extend = { workspace = true }
either = { workspace = true }

[build-dependencies]
metal-ungram = { workspace = true }

[lints]
workspace = true
